- upgraded all R and Python packages to current versions - went through the chapters to see what issues occur. Most are minor (renames), but at least two were not trivial so I now just commented them out:     - shifterator does not seem to work with recent packages (something about a YTick attribute missing)     - eli5 does not work with recent sklearn     - R keras no longer seems to work (?!), giving an error py_get_attr_impl(x, name, silent) : AttributeError: module 'tensorflow.keras' has no attribute '__version__'. I also commented out the R mnist example in ch 14 as mnist continuously timed oiut
This obviously needs more attention at some point...